stages:
  preprocess:
    cmd: python notebooks/preprocess.py  # (Assume you have a script to process raw data)
    deps:
      - data/raw/heart.csv
    outs:
      - data/processed/heart_processed.csv
  train:
    cmd: python notebooks/train_model.py
    deps:
      - data/processed/heart_processed.csv
      - notebooks/train_model.py
    outs:
      - models/heart-disease-model.pkl  # This can be used by MLFlow later
